meta:
  engine: 4.0.5
  version: 1.0
  author: darkpear
units:
  # Key spacing variables (Kailh Choc)
  kx: cx
  ky: cy
  # Padding variables
  px: kx + 2
  py: ky + 2
points:
  zones:
    matrix:
      columns:
        left:
        middle:
        right:
      rows:
        top:
        bottom:
