meta:
  engine: 4.0.2
  version: 1.0
  author: darkpear
units:
  # Key spacing variables (Kailh Choc)
  kx: cx
  ky: cy
  # Padding variables
  px: kx + 2
  py: ky + 2
points:
  zones:
    matrix:
      columns:
        left:
        middle:
        right:
      rows:
        bottom:
        top:
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_left_top
          shift: [-0.6px, 2py]
        - ref: matrix_right_top
          shift: [0.6px, 2py]
        - ref: matrix_right_bottom
          shift: [0.6px, -0.6py]
        - ref: matrix_left_bottom
          shift: [-0.6px, -0.6py]
  # Combination preview showing outline and keys.
  combo:
    - name: board
    - operation: subtract
      name: keys
