meta:
  engine: 4.0.5
  version: 1.0
  author: darkpear
points:
  zones:
    matrix:
      anchor:
        rotate: 5
      columns:
        outer:
        stretch:
          key.stagger: 4
        pinky:
          key.stagger: 2
        ring:
          key.splay: -0
          key.origin: [-12, -19]
          key.stagger: -0
        middle:
          key.stagger: 5
        index:
          key.stagger: -6
        inner:
          key.stagger: -2
        very-inner:
      rows:
        bottom:
        home:
        top:
        number:
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-34, -21]
      columns:
        nearer:
        near:
          key.spread: 21
          key.splay: -10
          key.origin: [-11.75, -9]
        home:
          key.spread: 21
          key.splay: -12
          key.origin: [-11.75, -9]
        far:
          key.spread: 21
          key.splay: -12
          key.origin: [-9.5, -9]
      rows:
        thumb:
  rotate: -20
  mirror:
    ref: matrix_pinky_home
    distance: 250
